nama: 単体テストの実行
on:
  push:
    branches:
      - dvelop
jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: 単体テスト
    steps:
      - name: チェックアウト
        uses: action/checkout@v2
      - name: パッケージのインストール
        run: npm ci
      - name: 単体テストの実行
        run: npm run test
